# Generated by Django 4.1.7 on 2023-04-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='users',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
