# Generated by Django 4.1.7 on 2023-04-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
