# Generated by Django 4.1.7 on 2023-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.BooleanField(default=False)),
                ('no', models.BooleanField(default=False)),
            ],
        ),
    ]
