# Generated by Django 4.1.7 on 2023-05-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_deleteform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deleteForm',
            new_name='deleteModel',
        ),
    ]
