# Generated by Django 4.1.7 on 2023-05-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_deleteform_deletemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruduser',
            name='password',
        ),
    ]
